

<LoginCard@MDCard>:
    style: "elevated"
    pos_hint: {"center_x": .5, "center_y": .5}
    padding: "20dp"
    size_hint: None, None
    width: "500dp"
    adaptive_height: True
    orientation: "vertical"
    spacing: "20dp"


<LoginLabel@MDLabel>:
    adaptive_size: True
    font_style: "Headline"
    role: "large"
    pos_hint: {"center_x": .5, "center_y": .5}


<LoginTextButton@MDButton>:
    style: "text"
    adaptive_height: True
    pos_hint: {"center_x": .5}
